Added Overwatch Rank Manager plugin.
NebulousCloud/helix-plugins pull request #10
Opened 2019-12-07 23:20 UTC by garytate

2019-12-08 07:00 UTC, alexgrist requested changes

2019-12-08 07:00 UTC, alexgrist commented on rankmanager.lua
> +OWRankManager = OWRankManager or {}
Creating globals is not needed or advised as they're less efficient and the plugin functionality is self contained and likely wouldn't need to be called at all from outside of the plugin (which is what hooks are for)

2019-12-08 07:00 UTC, alexgrist commented on rankmanager.lua
> +OWRankManager.FindFaction = function(player)
Using FACTION_* globals as the `rankTable` key would avoid the need for a faction lookup function, it would need to be created in a hook that is called after factions are initialized.

2019-12-08 10:46 UTC, garytate commented on rankmanager.lua
> +OWRankManager.FindFaction = function(player)
Done

2019-12-08 10:46 UTC, garytate commented on rankmanager.lua
> +OWRankManager = OWRankManager or {}
Sorted

2019-12-10 22:07 UTC, alexgrist approved these changes

2019-12-10 22:08 UTC, alexgrist commented on rankmanager.lua
> +ix.config.Add("allowRankManager", false, "Enable/Disable Overwatch ability to manage ranks.", nil, {
Is there much point in having a toggle for this when plugins themselves can be disabled? Not an issue just unsure if it's really worth having

2019-12-22 00:49 UTC, merged