Added doorkick plugin :)
NebulousCloud/helix-plugins pull request #39
Opened 2020-02-05 15:13 UTC by jopnine

I shall improve this on the future

2020-02-05 15:15 UTC, jopnine commented on doorkick/sh_plugin.lua
> +PLUGIN.description = "Adds doorkick to HL2RP."
I shall make a better desc in the future

2020-02-11 21:03 UTC, impulsh requested changes

2020-02-11 21:03 UTC, impulsh commented on doorkick/sh_plugin.lua
> +
Missing a license

2020-02-11 21:03 UTC, impulsh commented on doorkick/sh_plugin.lua
> +
`PLUGIN.schema` should be `"HL2 RP"`

2020-02-11 21:03 UTC, impulsh commented on doorkick/sh_plugin.lua
> +ix.config.Add("strneeded", 0.5, "How much strength is needed to kick a dor.", nil, {
Typo: `dor` instead of `door`

2020-02-11 21:03 UTC, impulsh commented on doorkick/sh_plugin.lua
> +									print(client:GetCharacter():GetAttribute("str", 0))
This print should be removed

2020-02-11 21:03 UTC, impulsh commented on doorkick/sh_plugin.lua
> +						print(client:GetCharacter():GetAttribute("str", 0))
This print should be removed

2020-02-11 21:03 UTC, impulsh commented on doorkick/sh_plugin.lua
> +		print(client:IsCombine())
These prints should be removed

2020-02-11 21:03 UTC, impulsh commented on doorkick/sh_plugin.lua
> +						timer.Simple( 0.5, function()
`ForceSequence` callback should be used here too

2020-04-13 03:11 UTC, closed without merging