New plugin
NebulousCloud/helix-plugins pull request #50
Opened 2020-03-09 19:54 UTC by lechu2375

2020-03-15 05:47 UTC, impulsh requested changes

2020-03-15 05:47 UTC, impulsh commented on sh_legshoot.lua
> +PLUGIN.name = "Legs wyjebnik"
Full English title would be preferred

2020-03-15 05:47 UTC, impulsh commented on sh_legshoot.lua
> +PLUGIN.license =  "MIT not for use on Kaktusownia"
The full MIT license text is required

2020-03-15 05:47 UTC, impulsh commented on sh_legshoot.lua
> +PLUGIN.description = "Now hitting right in the legs causes injures."
You should describe how to customize the plugin (e.g how to add ignored factions) in `PLUGIN.readme`

2020-03-15 05:47 UTC, impulsh commented on sh_legshoot.lua
> +        [FACTION_OTA] = true
This should probably be made a comment since you can't be sure that users will have `FACTION_OTA` in their schema

2020-03-16 17:10 UTC, lechu2375 commented
https://github.com/lechu2375/helix-lechu2375

2020-03-16 17:10 UTC, closed without merging